name: AlchemicTools
main: me.alchemi.alchemictools.Tools
version: ${project.version}
author: Alchemi
description: A plugin which contains some tools helpful for staff (and players).
depend:
- AlchemicLibrary
softdepend:
- PlaceholderAPI
- MVdWPlaceholderAPI
- ChatControl
- PlotSquared

commands:
   smite:
      usage: /smite <heathen>
      description: SEND A BOLT OF LIGHTING TO THAT HEATHEN.
      permission: alchemictools.smite
      aliases:
      - wrath
      
   vanish:
      usage: /vanish [special]
      description: Toggle vanish.
      permission: alchemictools.vanish
      aliases:
      - v
      
   staffchat:
      usage: /staffchat [message]
      description: Toggle staffchat usage or send a singular message.
      aliases:
      - helpop
      - adminchat
      - ho
      - ac
      - sc
      
   sudo:
      usage: /sudo <player> <command>
      description: Force a player to run a command.
      permission: alchemictools.sudo
          
   invsee:
      usage: /invsee <player> [armour|potions|inventory]
      description: Look at a players inventory
      permission: alchemictools.invsee
   
   reboot:
      usage: /reboot [delay] [reason]
      description: Restart the server with a delay.
      permission: alchemictools.restartserver
      aliases:
      - restartserver
   
   tools:
      usage: /tools <reload>
      description: AlchemicTools base command.
      permission: alchemictools.tools
      aliases:
      - admintools
      
   reportbug:
      usage: /reportbug "<title>" "[description]"
      description: Report a bug. Remember to use the ".
      permission: alchemictools.reportbug
      aliases:
      - bugs
      - bug
      
permissions:
   alchemictools.smite:
      description: Permission to SMITE HEATHENS.
      default: op
      
   alchemictools.vanish.*:
      children:
        alchemictools.vanish: true
        alchemictools.vanish.special: true
        
   alchemictools.vanish:
      description: Permission to vanish.
      default: op
      children:
        alchemictools.vanish.see: true
        alchemictools.vanish.notify: true
      
   alchemictools.vanish.see:
      description: Permission to see vanished players.
      default: op
   
   alchemictools.vanish.notify:
      description: Get notified when a player goes into vanish.
      default: op
      
   alchemictools.vanish.special:
      description: Vanish specially.
      default: false
      children:
        alchemictools.vanish.special.see: true
        alchemictools.vanish.special.notify: true
   
   alchemictools.vanish.special.see:
      description: See a special vanished player.
      default: false
      
   alchemictools.vanish.special.notify:
      description: Get notified when an admin goes into vanish.
      default: false
   
   alchemictools.staffchat:
      description: Permission to use the staff chat.
      default: op
      
   alchemictools.helpop:
      description: Permission to cry for help.
      default: true
      
   alchemictools.sudo:
      description: Permission to sudo a player.
      default: op
      
   alchemictools.invsee:
      description: Permission to see a players inventory.
      default: op
   
   alchemictools.restartserver:
      description: Permission to restart the server.
      default: op
   
   alchemictools.reportbug:
      description: Permission to report a bug.
      default: true
   
   alchemictools.tools.*:
      children:
        alchemictools.tools: true
        alchemictools.tools.reload: true
        alchemictools.tools.sort: true
        alchemictools.tools.autorefill: true
        alchemictools.tools.migrateuuid: true
        alchemictools.tools.getuuid: true
        alchemictools.tools.restore: true
        alchemictools.tools.notify: true
        alchemictools.tools.bugs.*: true
   
   alchemictools.tools:
      description: Permission for base command.
      default: op
      
   alchemictools.tools.reload:
      description: Permission to reload configs.
      default: op
      
   alchemictools.tools.sort:
      description: Permission to sort your inventory.
      default: op
      
   alchemictools.tools.autorefill:
      description: Your inventory automatically gets refilled.
      default: op
  
   alchemictools.tools.migrateuuid:
      description: Change an offline mode players uuid to its online one.
      default: false
      
   alchemictools.tools.getuuid:
      description: Permission to get the uuid of another account.
      default: false
    
   alchemictools.tools.restore:
      description: Permission to restore backups.
      default: false
      
   alchemictools.tools.notify:
      description: Permission to get notified.
      default: false
   
   alchemictools.tools.bugs.*:
      children:
        alchemictools.tools.bugs.active: true
        alchemictools.tools.bugs.deactivate: true
        alchemictools.tools.bugs.list: true
        alchemictools.tools.bugs.trello.*: true
   
   alchemictools.tools.bugs.activate:
      description: Permission to active bug reporter.
      default: op
      
   alchemictools.tools.bugs.deactivate:
      description: Permission to deactivate bug reporter.
      default: op
      
   alchemictools.tools.bugs.list:
      description: Permission to list available bug reporters.
      default: op
   
   alchemictools.tools.bugs.trello.*:
      children:
        alchemictools.tools.bugs.trello.token: true
        alchemictools.tools.bugs.trello.token.generate: true
      
   alchemictools.tools.bugs.trello.token:
      description: Permission to input trello token.
      default: op
   
   alchemictools.tools.bugs.trello.token.generate:
      description: Permission to generate trello token.
      default: op